### ISSUE TITLE
[Improvement] - Password creation

### ISSUE THREAD

**Issue by DDeAlmeida** [Narwallets/narwallets-extension#12]
![image](https://user-images.githubusercontent.com/52310650/135633995-d1269723-53ec-4014-9b97-f5c95b63e706.png)

On this page, add a view button near the password to allow to check the password clearly.

Change "passwords don't match" by  "Passwords don't match"

**Comment by defe3a** [comment]
Thanks @DDeAlmeida. The typo has been corrected.

We are analyzing adding a button to see the password.

**Comment by defe3a** [comment]
Added button to see password!
