### ISSUE TITLE
[Bug/Improvement] - Account Import

### ISSUE THREAD

**Issue by DDeAlmeida** [Narwallets/narwallets-extension#13]
I'm importing Narwallet account ...
![image](https://user-images.githubusercontent.com/52310650/135636010-b944299a-5bde-4a96-9fcc-8e3b230bcd4e.png)
...
Oups, this is not my account ... So i Cancel...
![image](https://user-images.githubusercontent.com/52310650/135636155-15b8a306-1396-4abd-9f67-042b89dca745.png)
Oh !! He is here !!

--->
Cancel don't work

How to remove this account ?

**Comment by defe3a** [comment]
Hi @DDeAlmeida, this is working as designed. You are adding a read only account.

If you want to remove this account, you can select it on the Account list, click on More tab, select the Remove option.
