### ISSUE TITLE
Navigating to different networks after install stops expected registration flow

### ISSUE THREAD

**Issue by mikedotexe** [Narwallets/narwallets-extension#2]
Attached in a short video of what I did when I first installed the extension. Seems like I cannot get back to setting up an account and password if the network is switched.
I think this is a case of users doing the silliest things you'd never image as the developer. 😆 

![narwallets](https://user-images.githubusercontent.com/1042667/104492813-081e0e00-5589-11eb-987d-1f69bd16ed24.gif)

**Comment by luciotato** [comment]
good catch and
>I think this is a case of users doing the silliest things you'd never image as the developer
completely agree

**Comment by luciotato** [comment]
@mikedotexe: It's fixed now, and I uploaded v1.0.2 to the chrome web store for approval.
Thanks for the report!!
