### ISSUE TITLE
Decimal value with point when send near token to other near wallet

### ISSUE THREAD

**Issue by danghuy174** [Narwallets/narwallets-extension#7]
[Steps to reproduce]
1. Open wallet 
2. Click "Send button" 
3. type received wallet in "Send to Account Id"
4. Fill "Amount in NEAR" with value have point. Example "51.8"
5. Click "OK"

[Expected result]
Send amount Near to Account ID (received wallet)

[Actual result]
Can't send Near, and show raise a error "The number ... cannot convert to BigInt because it is not a interger"

**Comment by luciotato** [comment]
fixed!
